import os
import json
import cv2
import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

# Page config
st.set_page_config(
    page_title="Smart Waste AI",
    page_icon="♻️",
    layout="wide"
)

# Class names — all models output in alphabetical order: glass, metal, paper, plastic
CLASS_NAMES = ["glass", "metal", "paper", "plastic"]

# CLIP is not a selectable model in this app — it's used internally, live at
# inference time, to power Feature Fusion's second input branch and the CLIP
# Verify fallback below. Downloaded from the HuggingFace Hub by name, no local
# checkpoint file needed.
CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"

# Feature Fusion needs a local .tflite file (converted from 03_Feature_Fusion.ipynb's
# .keras output) — place it in the same directory as this app. It's a dual-input
# model (image + CLIP feature), so it ALSO needs CLIP loaded live at inference time
# (see FUSION_MODELS handling below).
FUSION_MODEL_FILENAME = "resnet50_clip_fusion_final.tflite"

# Single source-of-truth results file — accuracy/per-class metrics/model size for
# the Model Comparison tab. Generated by evaluating each model's ACTUAL deployed
# file (not an earlier checkpoint) on the shared 845-image test split. Regenerate
# this if any model file above is retrained/replaced — see the notebooks cited in
# each entry's "source" field.
MODEL_RESULTS_FILENAME = "model_results.json"


@st.cache_data
def load_model_results():
    """Loads model_results.json, or None if it's missing (Compare tab handles
    that gracefully rather than crashing the whole app)."""
    if not os.path.exists(MODEL_RESULTS_FILENAME):
        return None
    with open(MODEL_RESULTS_FILENAME) as f:
        return json.load(f)


# Model config — the 4 models offered in the UI.
MODELS = {
    "CNN": "AdvancedCNN_none_classweight.keras",
    "MobileNetV2": "mobilenetv2_garbage_classifier_4class.keras",
    "ResNet50": "resnet50_model_quantized.tflite",
    "ResNet50+CLIP": FUSION_MODEL_FILENAME,
}

# CLIP Verify: an optional per-model toggle for CNN/MobileNetV2/ResNet50 that
# double-checks low-confidence predictions using CLIP Linear Probe (needs the
# small trained head saved from 02_CLIP_LinearProbe.ipynb, NOT zero-shot —
# Linear Probe is meaningfully more accurate, 90.65% vs 86.86%).
CLIP_LINEAR_PROBE_FILENAME = "clip_linear_probe.pt"
CLIP_VERIFY_MODELS = {"CNN", "MobileNetV2", "ResNet50"}
CLIP_VERIFY_DEFAULT_THRESHOLD = 0.90

# Models that need a local .keras/.tflite file AND CLIP loaded live (both frameworks
# resident in memory at once — the heaviest combination in this app by far).
FUSION_MODELS = {"ResNet50+CLIP"}

# Each model was trained with a different input normalization
PREPROCESS_FUNCS = {
    "CNN": lambda arr: arr / 255.0,              # AdvancedCNN: rescale=1./255
    "MobileNetV2": mobilenet_preprocess,          # scales to [-1, 1]
    "ResNet50": resnet_preprocess,                # ImageNet mean-subtraction
    # CLIP has no entry here — CLIPProcessor does its own resize/normalize
    # internally, so none of this pipeline applies to Feature Fusion's CLIP branch.
}


def preprocess_image(pil_image: Image.Image) -> np.ndarray:
    """Reproduce, pixel-pipeline-for-pixel-pipeline, what every current model
    checkpoint was actually trained with: resize original photo -> 224x224
    (nearest). Returns a float32 (224, 224, 3) array — normalization
    (preprocess_input) is applied separately afterward.

    All 4 models (CNN / MobileNetV2 / ResNet50 / Feature Fusion's ResNet50
    branch) share this same plain-resize pipeline — no cropping or background
    removal is used by any deployed checkpoint."""
    arr = np.array(pil_image.convert("RGB"))
    arr = cv2.resize(arr, (224, 224), interpolation=cv2.INTER_NEAREST)
    return arr.astype(np.float32)

# Recycling info
RECYCLE_INFO = {
    "glass": {
        "bin": "Green Bin",
        "color": "#2ecc71",
        "icon": "🍾",
        "description": "Glass bottles and jars are 100% recyclable. Rinse before recycling.",
        "tip": "Do not break glass before recycling.",
    },
    "metal": {
        "bin": "Metal Recycling Bin",
        "color": "#3498db",
        "icon": "🥫",
        "description": "Aluminum cans, tin cans, and metal containers are recyclable. Rinse clean.",
        "tip": "Crush cans to save space.",
    },
    "paper": {
        "bin": "Blue Bin",
        "color": "#9b59b6",
        "icon": "📄",
        "description": "Newspapers, magazines, cardboard, and office paper are recyclable. Keep dry.",
        "tip": "Remove plastic windows from envelopes.",
    },
    "plastic": {
        "bin": "Yellow Bin",
        "color": "#f39c12",
        "icon": "🧴",
        "description": "Plastic bottles and containers (check recycling number). Rinse before recycling.",
        "tip": "Check the number on the bottom — #1 and #2 are most recyclable.",
    },
}


# Load model with compatibility fix
def load_model_compat(path):
    # Feature Fusion: needs the local .tflite file AND a live CLIP encoder
    if path == FUSION_MODEL_FILENAME:
        return load_fusion_model()

    # .tflite files use TFLite interpreter
    if path.endswith(".tflite"):
        interpreter = tf.lite.Interpreter(model_path=path)
        interpreter.allocate_tensors()
        return interpreter

    # .keras files load directly
    if path.endswith(".keras"):
        return tf.keras.models.load_model(path, compile=False)

    raise ValueError(f"Unrecognized model file type: {path}")


def _clip_deps_available() -> bool:
    """True if torch + transformers are importable. Both Feature Fusion and
    CLIP Verify need them to load a live CLIP encoder at inference time, even
    though CLIP itself isn't a selectable model in this app anymore."""
    try:
        import torch  # noqa: F401
        import transformers  # noqa: F401
        return True
    except ImportError:
        return False


def load_clip_model():
    """Load CLIP exactly as in 01_CLIP_ZeroShot.ipynb Section 4 — same model name,
    same eval() mode, same device selection. Returns a small bundle dict instead of
    a bare model since get_clip_feature() also needs the processor + device."""
    import torch
    from transformers import CLIPModel, CLIPProcessor

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = CLIPModel.from_pretrained(CLIP_MODEL_NAME).to(device)
    processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME)
    model.eval()
    return {"model": model, "processor": processor, "device": device}


def load_fusion_model():
    """Load BOTH halves the Feature Fusion model needs: the trained dual-input
    TFLite interpreter (quantized, ~24MB vs the original 200MB .keras — same
    dynamic-range quantization used for the standalone ResNet50 model), and a
    frozen CLIP encoder (to compute the 512-d feature its second input branch
    expects). Mirrors 03_Feature_Fusion.ipynb Section 6.

    This is still the heaviest load in the app — full ResNet50 backbone (via the
    fusion model) + full CLIP (PyTorch) resident in memory at the same time, for
    as long as this model stays selected — quantizing the .tflite only shrinks
    the on-disk/weight footprint, not the fact that two frameworks run together."""
    interpreter = tf.lite.Interpreter(model_path=FUSION_MODEL_FILENAME)
    interpreter.allocate_tensors()
    clip_bundle = load_clip_model()
    return {"interpreter": interpreter, "clip": clip_bundle}


def get_clip_feature(clip_bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """Frozen CLIP image EMBEDDING (512-d, L2-normalized) — NOT zero-shot
    classification against text prompts. Same extraction used to build the
    training features in 02_CLIP_LinearProbe.ipynb / 03_Feature_Fusion.ipynb:
    vision_model -> visual_projection -> L2 normalize (bypasses the
    get_image_features() wrapper — see those notebooks for why)."""
    import torch

    model = clip_bundle["model"]
    processor = clip_bundle["processor"]
    device = clip_bundle["device"]

    with torch.no_grad():
        inputs = processor(images=[pil_image], return_tensors="pt").to(device)
        vision_outputs = model.vision_model(pixel_values=inputs["pixel_values"])
        pooled_output = vision_outputs.pooler_output
        feats = model.visual_projection(pooled_output)
        feats = feats / feats.norm(dim=-1, keepdim=True)

    return feats.cpu().numpy()  # shape (1, 512)


def predict_fusion(bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """Dual-branch inference, mirroring 03_Feature_Fusion.ipynb exactly:
    - ResNet50 branch: plain resize (Method A) + resnet50.preprocess_input,
      same pipeline as the standalone ResNet50 model above.
    - CLIP branch: frozen 512-d feature from get_clip_feature() above.
    Both feed into the trained fusion head via the TFLite interpreter. Tensors
    are matched by NAME, not fixed index — TFLite conversion doesn't guarantee
    input_details order matches the original Keras model's input list order
    (confirmed: this file lists clip_feature at index 0, image at index 1).
    Returns (1, 4) in CLASS_NAMES order, same as every other model's predictions."""
    interpreter = bundle["interpreter"]
    clip_bundle = bundle["clip"]

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    img_array = preprocess_image(pil_image)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = resnet_preprocess(img_array).astype(np.float32)

    clip_feature = get_clip_feature(clip_bundle, pil_image).astype(np.float32)

    for detail in input_details:
        if "image" in detail["name"]:
            interpreter.set_tensor(detail["index"], img_array)
        elif "clip_feature" in detail["name"]:
            interpreter.set_tensor(detail["index"], clip_feature)

    interpreter.invoke()
    predictions = interpreter.get_tensor(output_details[0]["index"])
    return predictions


def load_clip_verify_bundle():
    """CLIP Verify helper: frozen CLIP encoder + a small trained Linear Probe
    head (512 -> 4), used to double-check CNN/MobileNetV2/ResNet50 predictions
    when their own confidence is low. Mirrors 02_CLIP_LinearProbe.ipynb.

    ⚠️ Be upfront about this, including in the UI: evaluated on the 845-image
    shared test split at a threshold fixed in advance (90%, not searched —
    see clip_verify_threshold_search.py for the validation-set-only search
    this should be paired with), CLIP Verify did NOT beat ResNet50 alone —
    96.21% combined vs. 97.16% for ResNet50 alone (confirmed via
    04_Visualize_result_model.ipynb, Figure 8, using real per-image
    predictions from resnet50_predictions.csv + clip_linearprobe_predictions.csv).
    Figure 5 in that same notebook shows why: ResNet50's confidence
    distribution overlaps heavily between its correct and incorrect
    predictions on these clean, studio-style dataset photos, so a simple
    confidence cutoff can't cleanly separate "trust me" from "ask CLIP."
    This toggle exists for experimentation and for real-world /
    out-of-distribution photos, where the effect is untested and may differ —
    not because it's confirmed to help on the benchmark images the model was
    graded on."""
    import torch
    import torch.nn as nn

    class LinearProbeHead(nn.Module):
        def __init__(self, in_dim=512, n_classes=4):
            super().__init__()
            self.fc = nn.Linear(in_dim, n_classes)

        def forward(self, x):
            return self.fc(x)

    clip_bundle = load_clip_model()
    device = clip_bundle["device"]

    probe = LinearProbeHead().to(device)
    probe.load_state_dict(torch.load(CLIP_LINEAR_PROBE_FILENAME, map_location=device))
    probe.eval()

    return {"clip": clip_bundle, "probe": probe}


def predict_clip_verify(bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """CLIP Linear Probe inference — frozen CLIP feature -> trained Linear
    layer -> softmax. Same math as 02_CLIP_LinearProbe.ipynb Section 7.
    Returns (1, 4) in CLASS_NAMES order."""
    import torch

    clip_bundle = bundle["clip"]
    probe = bundle["probe"]
    device = clip_bundle["device"]

    clip_feature = get_clip_feature(clip_bundle, pil_image)  # (1, 512) numpy, frozen CLIP

    with torch.no_grad():
        feat_tensor = torch.tensor(clip_feature, dtype=torch.float32).to(device)
        logits = probe(feat_tensor)
        probs = torch.softmax(logits, dim=1).cpu().numpy()

    return probs


def predict_with_model(model, img_array):
    # TFLite interpreter
    if isinstance(model, tf.lite.Interpreter):
        input_details = model.get_input_details()
        output_details = model.get_output_details()
        # Cast to whatever dtype this specific .tflite file actually expects.
        # NOTE: if this file was created with full-integer quantization, it may expect
        # raw uint8 [0,255] input instead of the preprocessed float array — check the
        # conversion script that produced resnet50_model_quantized.tflite to confirm.
        input_dtype = input_details[0]['dtype']
        model.set_tensor(input_details[0]['index'], img_array.astype(input_dtype))
        model.invoke()
        return model.get_tensor(output_details[0]['index'])
    # Keras model
    return model.predict(img_array, verbose=0)


@st.cache_resource
def load_model(path):
    return load_model_compat(path)


@st.cache_resource
def get_clip_verify_bundle():
    return load_clip_verify_bundle()


# Custom CSS
st.markdown("""
<style>
    .stMainBlockContainer {
        padding-top: 30px !important;
    }
    .prediction-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 16px;
        padding: 2rem;
        color: white;
        text-align: center;
        margin: 1rem 0;
    }
    [data-theme="dark"] .prediction-card {
        background: linear-gradient(135deg, #4a5acf 0%, #5a3d8a 100%);
    }
    .prediction-label {
        font-size: 1rem;
        opacity: 0.9;
    }
    .prediction-value {
        font-size: 2.5rem;
        font-weight: 700;
        margin: 0.5rem 0;
    }
    .confidence-bar {
        background: rgba(255,255,255,0.3);
        border-radius: 10px;
        height: 12px;
        overflow: hidden;
        margin: 0.5rem 0;
    }
    .confidence-fill {
        height: 100%;
        border-radius: 10px;
        background: white;
    }
    .info-card {
        background: var(--secondary-background-color);
        color: var(--text-color);
        border-radius: 12px;
        padding: 1.5rem;
        margin: 0.5rem 0;
        border-left: 4px solid;
    }
    .model-unavailable {
        color: #e74c3c;
        font-size: 0.8rem;
    }
    [data-theme="dark"] .stProgress > div > div > div > div {
        background-color: var(--text-color);
    }
</style>
""", unsafe_allow_html=True)

# Tabs
tab_home, tab_compare, tab_about = st.tabs(["🏠 Home", "📊 Compare", "ℹ️ About"])

with tab_home:
    # Left-right layout
    col_left, col_right = st.columns([1, 1])

    with col_left:
        # Model selector (segmented control)
        st.markdown("**Select Model**")
        model_labels = []
        model_files = {}
        for name, filename in MODELS.items():
            if name in FUSION_MODELS:
                # Needs BOTH the local .tflite file AND torch/transformers installed.
                available = os.path.exists(filename) and _clip_deps_available()
            else:
                available = os.path.exists(filename)
            model_files[name] = available
            if available:
                model_labels.append(name)
            else:
                model_labels.append(f"{name} (Not trained)")

        selected_model_label = st.segmented_control(
            "Model",
            model_labels,
            label_visibility="collapsed",
            default="ResNet50",
        )

        selected_model = selected_model_label.replace(" (Not trained)", "") if selected_model_label else "ResNet50"
        model_available = model_files.get(selected_model, False)

        # CLIP Verify toggle — only offered for CNN/MobileNetV2/ResNet50
        # (Feature Fusion already includes CLIP, no point toggling)
        use_clip_verify = False
        clip_verify_threshold = CLIP_VERIFY_DEFAULT_THRESHOLD
        clip_verify_available = os.path.exists(CLIP_LINEAR_PROBE_FILENAME) and _clip_deps_available()

        if selected_model in CLIP_VERIFY_MODELS:
            if clip_verify_available:
                use_clip_verify = st.toggle(
                    "🔍 CLIP Verify",
                    help=f"When ON, predictions with confidence below "
                         f"{CLIP_VERIFY_DEFAULT_THRESHOLD*100:.0f}% get double-checked by CLIP "
                         "Linear Probe. Tested on the benchmark test set this did NOT "
                         "improve accuracy (confidence isn't a reliable signal for this "
                         "model) — provided for experimentation, especially on real-world "
                         "photos the model wasn't trained on.",
                )
            else:
                st.caption("⚠️ CLIP Verify unavailable — missing `clip_linear_probe.pt` or CLIP dependencies.")

        # Upload photo
        uploaded_file = st.file_uploader(
            "Upload a photo of waste",
            type=["jpg", "jpeg", "png", "webp"],
        )

        # Camera input (toggle)
        use_camera = st.toggle("📷 Camera Mode")
        camera_file = st.camera_input("Take a photo") if use_camera else None

        # Use camera if available, otherwise use uploaded file
        if camera_file is not None:
            image = Image.open(camera_file).convert("RGB")
        elif uploaded_file is not None:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption="Uploaded Image", width=200)
        else:
            image = None

        # Start Detection button
        detect_clicked = st.button("🔍 Start Detection", use_container_width=True)

    with col_right:
        if not model_available:
            st.warning(f"⚠️ {selected_model} model is not trained yet. Please select CNN model.")
        elif image is None:
            st.info("📷 Please upload an image or take a photo")
        elif not detect_clicked:
            st.info("⬆️ Upload/take a photo and click Start Detection")
        else:
            # Run prediction
            model = load_model(MODELS[selected_model])

            if selected_model in FUSION_MODELS:
                # Dual-branch: ResNet50-style preprocessing for the image input,
                # plus a live CLIP feature for the second input (see predict_fusion).
                with st.spinner(f"AI Detecting with {selected_model}..."):
                    predictions = predict_fusion(model, image)
                    pred_index = np.argmax(predictions[0])
                    pred_class = CLASS_NAMES[pred_index]
                    confidence = float(predictions[0][pred_index]) * 100
            else:
                # Step 1+2: reproduce this model's training-time pipeline (resize
                # -> normalize) — all 3 remaining models share the same resize step.
                img_array = preprocess_image(image)
                img_array = np.expand_dims(img_array, axis=0)

                # Step 3: use this model's own normalization — not a shared /255.0 for everything
                img_array = PREPROCESS_FUNCS[selected_model](img_array)

                with st.spinner(f"AI Detecting with {selected_model}..."):
                    predictions = predict_with_model(model, img_array)
                    pred_index = np.argmax(predictions[0])
                    pred_class = CLASS_NAMES[pred_index]
                    confidence = float(predictions[0][pred_index]) * 100

                # CLIP Verify: only kicks in if the toggle is on AND this
                # prediction's own confidence fell below the chosen threshold.
                # See load_clip_verify_bundle()'s docstring — this is NOT
                # confirmed to improve accuracy on the benchmark test images.
                if use_clip_verify and (confidence / 100.0) < clip_verify_threshold:
                    verify_bundle = get_clip_verify_bundle()
                    with st.spinner("Confidence low — verifying with CLIP..."):
                        clip_predictions = predict_clip_verify(verify_bundle, image)
                        predictions = clip_predictions
                        pred_index = np.argmax(predictions[0])
                        pred_class = CLASS_NAMES[pred_index]
                        confidence = float(predictions[0][pred_index]) * 100
                    st.caption(f"🔍 {selected_model}'s confidence was below "
                               f"{clip_verify_threshold*100:.0f}% — final answer verified/overridden by CLIP.")
                elif use_clip_verify:
                    st.caption(f"✅ {selected_model} was confident enough — used directly, CLIP not consulted.")

            info = RECYCLE_INFO[pred_class]

            # Prediction card
            st.markdown(f"""
            <div class="prediction-card">
                <div class="prediction-label">Prediction</div>
                <div class="prediction-value">{info['icon']} {pred_class.title()}</div>
                <div class="confidence-bar">
                    <div class="confidence-fill" style="width: {confidence}%"></div>
                </div>
                <div class="prediction-label">Confidence: {confidence:.1f}%</div>
            </div>
            """, unsafe_allow_html=True)

            # All probabilities
            st.markdown("**📊 All Probabilities**")
            probs = {CLASS_NAMES[i]: float(predictions[0][i]) * 100 for i in range(len(CLASS_NAMES))}
            sorted_probs = dict(sorted(probs.items(), key=lambda x: x[1], reverse=True))
            for cls, prob in sorted_probs.items():
                st.progress(prob / 100, text=f"{cls.title()}: {prob:.1f}%")

            # Recycling guide
            st.markdown("**♻️ Recycling Guide**")
            col1, col2 = st.columns(2)
            with col1:
                st.markdown(f"""
                <div class="info-card" style="border-color: {info['color']}">
                    <strong>Bin:</strong> {info['bin']}<br>
                    <strong>Description:</strong> {info['description']}
                </div>
                """, unsafe_allow_html=True)
            with col2:
                st.markdown(f"""
                <div class="info-card" style="border-color: {info['color']}">
                    <strong>Tip:</strong> {info['tip']}
                </div>
                """, unsafe_allow_html=True)

with tab_compare:
    st.markdown("### 📊 Model Comparison")
    results = load_model_results()

    if results is None:
        st.warning(
            f"⚠️ `{MODEL_RESULTS_FILENAME}` not found next to app.py — "
            "this file holds the numbers for the charts below."
        )
    else:
        # Only the models actually selectable in the app — model_results.json also
        # keeps a "CLIP Linear Probe" entry for reference (used by the Colab
        # comparison notebook), but it's not a standalone deployable option here.
        model_names = [m for m in results["models"] if results["models"][m].get("file")]
        class_names = results["class_names"]
        test_n = results["test_set_size"]

        st.caption(
            f"Every number below comes from evaluating each model's actual deployed file "
            f"(the same .keras/.tflite in this repo) on the same shared {test_n}-image test split."
        )

        # --- Overall test accuracy ---
        st.markdown("#### Overall Test Accuracy")
        st.caption('Higher is better — the single number that answers "which model is most accurate?"')
        acc_df = pd.DataFrame({
            "Model": model_names,
            "Test Accuracy (%)": [results["models"][m]["test_accuracy"] * 100 for m in model_names],
        }).set_index("Model")
        st.bar_chart(acc_df, horizontal=True)

        cols = st.columns(len(model_names))
        for col, name in zip(cols, model_names):
            col.metric(name, f"{results['models'][name]['test_accuracy'] * 100:.2f}%")

        st.divider()

        # --- Per-class F1-score heatmap ---
        st.markdown("#### Per-Class F1-Score")
        st.caption(
            "Shows where each model struggles with a specific waste type. "
            "Darker green = better."
        )
        f1_df = pd.DataFrame(
            {
                name: [results["models"][name]["per_class"][c]["f1"] for c in class_names]
                for name in model_names
            },
            index=[c.title() for c in class_names],
        ).T
        st.dataframe(
            f1_df.style.format("{:.3f}").background_gradient(cmap="Greens", vmin=0.80, vmax=1.00)
        )

        st.divider()

        # --- Model size vs. accuracy trade-off ---
        st.markdown("#### Model Size vs. Accuracy")
        st.caption(
            "Bigger dot = bigger file. Bottom-left = small & fast, top-right = big & accurate — "
            "this trade-off is why MobileNetV2 exists for phones even though ResNet50 scores higher."
        )
        size_df = pd.DataFrame({
            "Model": model_names,
            "Size (MB)": [results["models"][m]["size_mb"] for m in model_names],
            "Test Accuracy (%)": [results["models"][m]["test_accuracy"] * 100 for m in model_names],
        })
        st.scatter_chart(size_df, x="Size (MB)", y="Test Accuracy (%)", size="Size (MB)", color="Model")

        st.divider()

        with st.expander("📁 Data sources & what's not shown yet"):
            for name in model_names:
                st.caption(f"**{name}** — {results['models'][name]['source']}")
            st.markdown(
                "Confusion matrices, per-image inference speed, and training curves for the "
                "final deployed models aren't included yet — the notebooks currently only "
                "*plot* those as images rather than printing the raw numbers, so they'd need "
                "to be re-exported as text/CSV first."
            )

with tab_about:
    st.markdown("## About Smart Waste AI")
    st.markdown("""
    ### What is this?
    AI-powered waste classification system. Upload a photo, and the AI identifies the waste type and guides proper disposal.

    ### How does it work?
    - Multiple AI models trained on waste images
    - Classifies into 4 categories: **Glass, Metal, Paper, Plastic**
    - Provides confidence scores for each category

    ### Supported Models
    | Model | Status |
    |-------|--------|
    | CNN | ✅ Available |
    | MobileNetV2 | ✅ Available |
    | ResNet50 | ✅ Available |
    | Feature Fusion (ResNet50+CLIP) | ✅ Available — dual-branch trained framework, 96.80% test accuracy |

    **CLIP Verify** (optional toggle for CNN/MobileNetV2/ResNet50): double-checks
    low-confidence predictions using CLIP Linear Probe. ⚠️ Tested on the benchmark
    test set, this did *not* improve accuracy — provided for experimentation on
    real-world photos instead.

    ### Supported Waste Types
    | Category | Examples |
    |----------|----------|
    | 🍾 Glass | Bottles, jars, windows |
    | 🥫 Metal | Cans, foil, containers |
    | 📄 Paper | Newspapers, cardboard, books |
    | 🧴 Plastic | Bottles, containers, packaging |

    ### Team
    Built for AI Course Assignment
    """)
