import os
import json
import time
import threading
import cv2
import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

# Page config
st.set_page_config(
    page_title="Smart Waste AI",
    page_icon="♻️",
    layout="wide"
)

# Class names — all models output in alphabetical order: glass, metal, paper, plastic
CLASS_NAMES = ["glass", "metal", "paper", "plastic"]

# CLIP is not a selectable model in this app — it's used internally, live at
# inference time, to power Feature Fusion's second input branch and the CLIP
# Verify fallback below. Downloaded from the HuggingFace Hub by name, no local
# checkpoint file needed.
CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"

# Feature Fusion needs a local .tflite file (converted from 03_Feature_Fusion.ipynb's
# .keras output) — place it in the same directory as this app. It's a dual-input
# model (image + CLIP feature), so it ALSO needs CLIP loaded live at inference time
# (see FUSION_MODELS handling below).
FUSION_MODEL_FILENAME = "resnet50_clip_fusion_final.tflite"

# Single source-of-truth results file — accuracy/per-class metrics/model size for
# the Model Comparison tab. Generated by evaluating each model's ACTUAL deployed
# file (not an earlier checkpoint) on the shared 845-image test split. Regenerate
# this if any model file above is retrained/replaced — see the notebooks cited in
# each entry's "source" field.
MODEL_RESULTS_FILENAME = "model_results.json"

# Static chart images exported from 04_Visualize_result_model.ipynb (Colab) and
# committed to the repo under this folder — for figures that aren't worth
# reimplementing live in matplotlib (e.g. confusion matrices, ROC curves).
# Overall Test Accuracy and Model Size vs. Accuracy stay as live matplotlib
# charts above/below this, driven directly by model_results.json.
FIGURES_DIR = "figures"


@st.cache_data
def load_model_results():
    """Loads model_results.json, or None if it's missing (Compare tab handles
    that gracefully rather than crashing the whole app)."""
    if not os.path.exists(MODEL_RESULTS_FILENAME):
        return None
    with open(MODEL_RESULTS_FILENAME) as f:
        return json.load(f)


# Model config — the 4 models offered in the UI.
MODELS = {
    "CNN": "AdvancedCNN_none_classweight.keras",
    "MobileNetV2": "mobilenetv2_garbage_classifier_4class.keras",
    "ResNet50": "resnet50_model_quantized.tflite",
    "ResNet50+CLIP": FUSION_MODEL_FILENAME,
}

# CLIP Verify: an optional per-model toggle for CNN/MobileNetV2/ResNet50 that
# double-checks low-confidence predictions using CLIP Linear Probe (needs the
# small trained head saved from 02_CLIP_LinearProbe.ipynb, NOT zero-shot —
# Linear Probe is meaningfully more accurate, 90.65% vs 86.86%).
CLIP_LINEAR_PROBE_FILENAME = "clip_linear_probe.pt"
CLIP_VERIFY_MODELS = {"CNN", "MobileNetV2", "ResNet50"}
CLIP_VERIFY_DEFAULT_THRESHOLD = 0.90

# Models that need a local .keras/.tflite file AND CLIP loaded live (both frameworks
# resident in memory at once — the heaviest combination in this app by far).
FUSION_MODELS = {"ResNet50+CLIP"}

# Each model was trained with a different input normalization
PREPROCESS_FUNCS = {
    "CNN": lambda arr: arr / 255.0,              # AdvancedCNN: rescale=1./255
    "MobileNetV2": mobilenet_preprocess,          # scales to [-1, 1]
    "ResNet50": resnet_preprocess,                # ImageNet mean-subtraction
    # CLIP has no entry here — CLIPProcessor does its own resize/normalize
    # internally, so none of this pipeline applies to Feature Fusion's CLIP branch.
}


def preprocess_image(pil_image: Image.Image) -> np.ndarray:
    """Reproduce, pixel-pipeline-for-pixel-pipeline, what every current model
    checkpoint was actually trained with: resize original photo -> 224x224
    (nearest). Returns a float32 (224, 224, 3) array — normalization
    (preprocess_input) is applied separately afterward.

    All 4 models (CNN / MobileNetV2 / ResNet50 / Feature Fusion's ResNet50
    branch) share this same plain-resize pipeline — no cropping or background
    removal is used by any deployed checkpoint."""
    arr = np.array(pil_image.convert("RGB"))
    arr = cv2.resize(arr, (224, 224), interpolation=cv2.INTER_NEAREST)
    return arr.astype(np.float32)

# Recycling info
RECYCLE_INFO = {
    "glass": {
        "bin": "Green Bin",
        "color": "#2ecc71",
        "icon": "🍾",
        "description": "Glass bottles and jars are 100% recyclable. Rinse before recycling.",
        "tip": "Do not break glass before recycling.",
    },
    "metal": {
        "bin": "Metal Recycling Bin",
        "color": "#3498db",
        "icon": "🥫",
        "description": "Aluminum cans, tin cans, and metal containers are recyclable. Rinse clean.",
        "tip": "Crush cans to save space.",
    },
    "paper": {
        "bin": "Blue Bin",
        "color": "#9b59b6",
        "icon": "📄",
        "description": "Newspapers, magazines, cardboard, and office paper are recyclable. Keep dry.",
        "tip": "Remove plastic windows from envelopes.",
    },
    "plastic": {
        "bin": "Yellow Bin",
        "color": "#f39c12",
        "icon": "🧴",
        "description": "Plastic bottles and containers (check recycling number). Rinse before recycling.",
        "tip": "Check the number on the bottom — #1 and #2 are most recyclable.",
    },
}


# Load model with compatibility fix
def load_model_compat(path):
    # Feature Fusion: needs the local .tflite file AND a live CLIP encoder
    if path == FUSION_MODEL_FILENAME:
        return load_fusion_model()

    # .tflite files use TFLite interpreter
    if path.endswith(".tflite"):
        interpreter = tf.lite.Interpreter(model_path=path)
        interpreter.allocate_tensors()
        return interpreter

    # .keras files load directly
    if path.endswith(".keras"):
        return tf.keras.models.load_model(path, compile=False)

    raise ValueError(f"Unrecognized model file type: {path}")


def _clip_deps_available() -> bool:
    """True if torch + transformers are importable. Both Feature Fusion and
    CLIP Verify need them to load a live CLIP encoder at inference time, even
    though CLIP itself isn't a selectable model in this app anymore."""
    try:
        import torch  # noqa: F401
        import transformers  # noqa: F401
        return True
    except ImportError:
        return False


def load_clip_model():
    """Load CLIP exactly as in 01_CLIP_ZeroShot.ipynb Section 4 — same model name,
    same eval() mode, same device selection. Returns a small bundle dict instead of
    a bare model since get_clip_feature() also needs the processor + device."""
    import torch
    from transformers import CLIPModel, CLIPProcessor

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = CLIPModel.from_pretrained(CLIP_MODEL_NAME).to(device)
    processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME)
    model.eval()
    return {"model": model, "processor": processor, "device": device}


def load_fusion_model():
    """Load BOTH halves the Feature Fusion model needs: the trained dual-input
    TFLite interpreter (quantized, ~24MB vs the original 200MB .keras — same
    dynamic-range quantization used for the standalone ResNet50 model), and a
    frozen CLIP encoder (to compute the 512-d feature its second input branch
    expects). Mirrors 03_Feature_Fusion.ipynb Section 6.

    This is still the heaviest load in the app — full ResNet50 backbone (via the
    fusion model) + full CLIP (PyTorch) resident in memory at the same time, for
    as long as this model stays selected — quantizing the .tflite only shrinks
    the on-disk/weight footprint, not the fact that two frameworks run together."""
    interpreter = tf.lite.Interpreter(model_path=FUSION_MODEL_FILENAME)
    interpreter.allocate_tensors()
    clip_bundle = load_clip_model()
    return {"interpreter": interpreter, "clip": clip_bundle}


def get_clip_feature(clip_bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """Frozen CLIP image EMBEDDING (512-d, L2-normalized) — NOT zero-shot
    classification against text prompts. Same extraction used to build the
    training features in 02_CLIP_LinearProbe.ipynb / 03_Feature_Fusion.ipynb:
    vision_model -> visual_projection -> L2 normalize (bypasses the
    get_image_features() wrapper — see those notebooks for why)."""
    import torch

    model = clip_bundle["model"]
    processor = clip_bundle["processor"]
    device = clip_bundle["device"]

    with torch.no_grad():
        inputs = processor(images=[pil_image], return_tensors="pt").to(device)
        vision_outputs = model.vision_model(pixel_values=inputs["pixel_values"])
        pooled_output = vision_outputs.pooler_output
        feats = model.visual_projection(pooled_output)
        feats = feats / feats.norm(dim=-1, keepdim=True)

    return feats.cpu().numpy()  # shape (1, 512)


def predict_fusion(bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """Dual-branch inference, mirroring 03_Feature_Fusion.ipynb exactly:
    - ResNet50 branch: plain resize (Method A) + resnet50.preprocess_input,
      same pipeline as the standalone ResNet50 model above.
    - CLIP branch: frozen 512-d feature from get_clip_feature() above.
    Both feed into the trained fusion head via the TFLite interpreter. Tensors
    are matched by NAME, not fixed index — TFLite conversion doesn't guarantee
    input_details order matches the original Keras model's input list order
    (confirmed: this file lists clip_feature at index 0, image at index 1).
    Returns (1, 4) in CLASS_NAMES order, same as every other model's predictions."""
    interpreter = bundle["interpreter"]
    clip_bundle = bundle["clip"]

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    img_array = preprocess_image(pil_image)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = resnet_preprocess(img_array).astype(np.float32)

    clip_feature = get_clip_feature(clip_bundle, pil_image).astype(np.float32)

    for detail in input_details:
        if "image" in detail["name"]:
            interpreter.set_tensor(detail["index"], img_array)
        elif "clip_feature" in detail["name"]:
            interpreter.set_tensor(detail["index"], clip_feature)

    interpreter.invoke()
    predictions = interpreter.get_tensor(output_details[0]["index"])
    return predictions


def load_clip_verify_bundle():
    """CLIP Verify helper: frozen CLIP encoder + a small trained Linear Probe
    head (512 -> 4), used to double-check CNN/MobileNetV2/ResNet50 predictions
    when their own confidence is low. Mirrors 02_CLIP_LinearProbe.ipynb.

    ⚠️ Be upfront about this, including in the UI: evaluated on the 845-image
    shared test split at a threshold fixed in advance (90%, not searched —
    see clip_verify_threshold_search.py for the validation-set-only search
    this should be paired with), CLIP Verify did NOT beat ResNet50 alone —
    96.21% combined vs. 97.16% for ResNet50 alone (confirmed via
    04_Visualize_result_model.ipynb, Figure 8, using real per-image
    predictions from resnet50_predictions.csv + clip_linearprobe_predictions.csv).
    Figure 5 in that same notebook shows why: ResNet50's confidence
    distribution overlaps heavily between its correct and incorrect
    predictions on these clean, studio-style dataset photos, so a simple
    confidence cutoff can't cleanly separate "trust me" from "ask CLIP."
    This toggle exists for experimentation and for real-world /
    out-of-distribution photos, where the effect is untested and may differ —
    not because it's confirmed to help on the benchmark images the model was
    graded on."""
    import torch
    import torch.nn as nn

    class LinearProbeHead(nn.Module):
        def __init__(self, in_dim=512, n_classes=4):
            super().__init__()
            self.fc = nn.Linear(in_dim, n_classes)

        def forward(self, x):
            return self.fc(x)

    clip_bundle = load_clip_model()
    device = clip_bundle["device"]

    probe = LinearProbeHead().to(device)
    probe.load_state_dict(torch.load(CLIP_LINEAR_PROBE_FILENAME, map_location=device))
    probe.eval()

    return {"clip": clip_bundle, "probe": probe}


def predict_clip_verify(bundle: dict, pil_image: Image.Image) -> np.ndarray:
    """CLIP Linear Probe inference — frozen CLIP feature -> trained Linear
    layer -> softmax. Same math as 02_CLIP_LinearProbe.ipynb Section 7.
    Returns (1, 4) in CLASS_NAMES order."""
    import torch

    clip_bundle = bundle["clip"]
    probe = bundle["probe"]
    device = clip_bundle["device"]

    clip_feature = get_clip_feature(clip_bundle, pil_image)  # (1, 512) numpy, frozen CLIP

    with torch.no_grad():
        feat_tensor = torch.tensor(clip_feature, dtype=torch.float32).to(device)
        logits = probe(feat_tensor)
        probs = torch.softmax(logits, dim=1).cpu().numpy()

    return probs


# One shared lock around ALL model inference. Live Mode runs predictions on a
# WebRTC worker thread while the Home tab may run one on the Streamlit script
# thread, and both can hit the SAME cached object (@st.cache_resource returns one
# instance per model file). A TFLite interpreter is not thread-safe -- concurrent
# set_tensor/invoke on one interpreter interleaves and returns garbage -- so every
# inference path serialises here. Purely a concurrency guard: no numerics change.
_INFERENCE_LOCK = threading.Lock()


def predict_with_model(model, img_array):
    with _INFERENCE_LOCK:
        return _predict_with_model_unlocked(model, img_array)


def _predict_with_model_unlocked(model, img_array):
    # TFLite interpreter
    if isinstance(model, tf.lite.Interpreter):
        input_details = model.get_input_details()
        output_details = model.get_output_details()
        # Cast to whatever dtype this specific .tflite file actually expects.
        # NOTE: if this file was created with full-integer quantization, it may expect
        # raw uint8 [0,255] input instead of the preprocessed float array — check the
        # conversion script that produced resnet50_model_quantized.tflite to confirm.
        input_dtype = input_details[0]['dtype']
        model.set_tensor(input_details[0]['index'], img_array.astype(input_dtype))
        model.invoke()
        return model.get_tensor(output_details[0]['index'])
    # Keras model
    return model.predict(img_array, verbose=0)


@st.cache_resource
def load_model(path):
    return load_model_compat(path)


@st.cache_resource
def get_clip_verify_bundle():
    return load_clip_verify_bundle()


# ─────────────────────────────────────────────────────────────────────────────
# Live Camera Mode
# ─────────────────────────────────────────────────────────────────────────────
# ⚠️ READ THIS BEFORE CHANGING ANYTHING BELOW — what Live Mode is and isn't:
#
# Every model in this app is a CLASSIFIER, not an object DETECTOR. The only
# thing any of these checkpoints outputs is a (1, 4) probability vector — there
# is no box/coordinate head anywhere. So Live Mode does NOT "find" objects in
# the frame. What it actually does:
#
#   1. Draws a fixed centre square as a FRAMING GUIDE ("put the item here") and
#      classifies only the pixels inside it. That box is an aiming reticle, not
#      a detection — and cropping to it also keeps the input closer to the
#      single-object, full-frame photos these models were trained on.
#   2. Colours the whole-frame border by the predicted class and overlays the
#      label + confidence for that region.
#   3. Optionally overlays a Grad-CAM box showing WHERE THE MODEL LOOKED. That
#      is an explainability heatmap computed from the classifier's own last conv
#      layer — still not object detection, and it is labelled as such on screen.
#
# Real bounding boxes would need a detector (YOLO etc.), i.e. training a new
# model, which is out of scope. Do not relabel any of this as "detection" in the
# UI without changing the underlying model first.

# ResNet50+CLIP is deliberately excluded: it runs a full PyTorch CLIP encoder
# per frame on top of the ResNet50 branch, which is far too slow for live video.
LIVE_MODELS = ["CNN", "MobileNetV2", "ResNet50"]

# Grad-CAM needs to backprop to an intermediate feature map, so it only works on
# the .keras models — a TFLite interpreter exposes no such tensor.
LIVE_GRADCAM_MODELS = {"CNN", "MobileNetV2"}

LIVE_LOW_CONFIDENCE = 0.60      # below this, the overlay goes grey + "Uncertain"
LIVE_UNCERTAIN_BGR = (150, 150, 150)
LIVE_GUIDE_BGR = (255, 255, 255)
LIVE_CAM_BGR = (0, 220, 255)    # Grad-CAM box (amber)

try:
    from streamlit_webrtc import webrtc_streamer, WebRtcMode
    import av  # noqa: F401  — streamlit_webrtc needs it; imported here to fail early
    _WEBRTC_AVAILABLE = True
except ImportError:
    _WEBRTC_AVAILABLE = False


def _hex_to_bgr(hex_color: str) -> tuple:
    """'#2ecc71' -> (113, 204, 46), because OpenCV wants BGR and RECYCLE_INFO
    stores web-style RGB hex."""
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return (b, g, r)


def roi_box(width: int, height: int, ratio: float) -> tuple:
    """Centre square framing guide, sized as `ratio` of the frame's short edge.
    Returns (x0, y0, x1, y1) in pixels."""
    side = int(min(width, height) * ratio)
    x0 = (width - side) // 2
    y0 = (height - side) // 2
    return x0, y0, x0 + side, y0 + side


@st.cache_resource
def get_gradcam_model(model_key: str):
    """Build a Grad-CAM gradient model: input -> (last conv feature map, output).

    Returns None (rather than raising) if the model cannot be introspected — the
    caller degrades to "no attention box" instead of taking the whole tab down.

    The last conv layer is found by scanning backwards for the first 4-D output,
    which resolves to `max_pooling2d_3` (14x14) on AdvancedCNN and `out_relu`
    (7x7x1280) on MobileNetV2 — both the standard Grad-CAM tap points."""
    try:
        model = load_model(MODELS[model_key])
        if isinstance(model, (tf.lite.Interpreter, dict)):
            return None
        # Keras 3: a model loaded from .keras may not expose .inputs until it has
        # been called once, so warm it up on a dummy batch first.
        model(np.zeros((1, 224, 224, 3), dtype=np.float32), training=False)

        last_conv = None
        for layer in reversed(model.layers):
            try:
                if len(layer.output.shape) == 4:
                    last_conv = layer
                    break
            except AttributeError:
                continue
        if last_conv is None:
            return None
        return tf.keras.models.Model(model.inputs, [last_conv.output, model.output])
    except Exception:
        return None


def compute_gradcam_box(grad_model, img_array: np.ndarray, class_index: int,
                        thresh: float = 0.5):
    """Grad-CAM heatmap -> bounding box of the strongest attention blob.

    `img_array` is the same (1, 224, 224, 3) preprocessed tensor the prediction
    used. Returns (x0, y0, x1, y1) NORMALIZED to [0, 1] within the ROI crop, or
    None if no region clears `thresh`.

    This box means "the model's evidence for this class concentrated here". It
    is NOT a detected object boundary."""
    try:
        with tf.GradientTape() as tape:
            conv_out, preds = grad_model(img_array, training=False)
            tape.watch(conv_out)
            score = preds[:, class_index]
        grads = tape.gradient(score, conv_out)
        if grads is None:
            return None

        weights = tf.reduce_mean(grads, axis=(0, 1, 2))
        cam = tf.reduce_sum(conv_out[0] * weights, axis=-1)
        cam = tf.nn.relu(cam).numpy()
        peak = float(cam.max())
        if peak <= 1e-8:
            return None
        cam = cam / peak

        mask = (cam >= thresh).astype(np.uint8) * 255
        mask = cv2.resize(mask, (224, 224), interpolation=cv2.INTER_LINEAR)
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not contours:
            return None
        x, y, w, h = cv2.boundingRect(max(contours, key=cv2.contourArea))
        return (x / 224.0, y / 224.0, (x + w) / 224.0, (y + h) / 224.0)
    except Exception:
        return None


class LiveSettings:
    """Shared, mutable settings + rolling results for Live Mode.

    Created once per session and stored in st.session_state. The Streamlit
    script thread WRITES the settings on every rerun (when the user moves a
    slider); the WebRTC worker thread only reads them, and writes the results
    back. Both directions are guarded by `lock`. Never touch st.session_state
    from the worker thread — that is not supported by Streamlit."""

    def __init__(self):
        self.lock = threading.Lock()
        # settings (written by the Streamlit script thread)
        self.model = None
        self.model_name = None
        self.grad_model = None
        self.roi_ratio = 0.70
        self.infer_every = 3
        self.ema_alpha = 0.50
        self.use_gradcam = False
        self.mirror = True
        # rolling state (written by the WebRTC worker thread)
        self.frame_i = 0
        self.smoothed = None        # np.ndarray (4,) — EMA of class probabilities
        self.cam_box = None
        self.latency_ms = None


def classify_roi(bgr_frame: np.ndarray, settings):
    """Crop the centre ROI and run it through the selected model's own
    training-time pipeline — identical to the Home tab: plain resize, then that
    model's own preprocess_input.

    Returns (probs (4,), gradcam_box_or_None, latency_ms). Deliberately reuses
    preprocess_image() and PREPROCESS_FUNCS so Live Mode and the Home tab can
    never drift apart on preprocessing."""
    height, width = bgr_frame.shape[:2]
    x0, y0, x1, y1 = roi_box(width, height, settings.roi_ratio)
    crop_rgb = cv2.cvtColor(bgr_frame[y0:y1, x0:x1], cv2.COLOR_BGR2RGB)

    img_array = preprocess_image(Image.fromarray(crop_rgb))
    img_array = np.expand_dims(img_array, axis=0)
    img_array = PREPROCESS_FUNCS[settings.model_name](img_array)

    started = time.perf_counter()
    predictions = predict_with_model(settings.model, img_array)
    latency_ms = (time.perf_counter() - started) * 1000.0

    probs = np.asarray(predictions[0], dtype=np.float32)

    cam_box = None
    if settings.use_gradcam and settings.grad_model is not None:
        cam_box = compute_gradcam_box(settings.grad_model, img_array, int(np.argmax(probs)))

    return probs, cam_box, latency_ms


def draw_live_overlay(bgr_frame: np.ndarray, settings, probs, cam_box, latency_ms):
    """Paint the framing guide, the class-coloured frame border, the label bar,
    the optional Grad-CAM attention box, and the latency readout."""
    height, width = bgr_frame.shape[:2]
    x0, y0, x1, y1 = roi_box(width, height, settings.roi_ratio)

    if probs is None:
        cv2.rectangle(bgr_frame, (x0, y0), (x1, y1), LIVE_GUIDE_BGR, 2)
        cv2.putText(bgr_frame, "Warming up...", (x0, max(y0 - 12, 20)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, LIVE_GUIDE_BGR, 2, cv2.LINE_AA)
        return bgr_frame

    index = int(np.argmax(probs))
    label = CLASS_NAMES[index]
    confidence = float(probs[index])
    confident = confidence >= LIVE_LOW_CONFIDENCE
    color = _hex_to_bgr(RECYCLE_INFO[label]["color"]) if confident else LIVE_UNCERTAIN_BGR

    # 1. Whole-frame border in the class colour. This hugs the frame on purpose:
    #    the result is a CLASSIFICATION of the ROI, not a localisation, so it
    #    would be dishonest to draw it tight around anything.
    cv2.rectangle(bgr_frame, (0, 0), (width - 1, height - 1), color, 10)

    # 2. Centre framing guide.
    cv2.rectangle(bgr_frame, (x0, y0), (x1, y1), LIVE_GUIDE_BGR, 2)

    # 3. Grad-CAM attention box, mapped from ROI-normalized coords back to px.
    if cam_box is not None:
        side = x1 - x0
        cx0 = x0 + int(cam_box[0] * side)
        cy0 = y0 + int(cam_box[1] * side)
        cx1 = x0 + int(cam_box[2] * side)
        cy1 = y0 + int(cam_box[3] * side)
        cv2.rectangle(bgr_frame, (cx0, cy0), (cx1, cy1), LIVE_CAM_BGR, 2)
        cv2.putText(bgr_frame, "model attention", (cx0, max(cy0 - 8, 14)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, LIVE_CAM_BGR, 1, cv2.LINE_AA)

    # 4. Label bar. OpenCV cannot render the emoji used elsewhere in the app, so
    #    this overlay is text-only by necessity.
    text = (f"{label.title()}  {confidence * 100:.1f}%" if confident
            else f"Uncertain ({label.title()} {confidence * 100:.0f}%)")
    (tw, th), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.9, 2)
    cv2.rectangle(bgr_frame, (10, 10), (10 + tw + 24, 10 + th + 24), color, -1)
    cv2.putText(bgr_frame, text, (22, 10 + th + 8),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2, cv2.LINE_AA)

    # 5. Bin hint + latency readout, both bottom-left. They sit here rather than
    #    under the label bar because the framing guide's top edge lands right
    #    about there at the default ROI ratio, and the text collided with it.
    hint = RECYCLE_INFO[label]["bin"] if confident else "Move closer / better light"
    cv2.putText(bgr_frame, hint, (14, height - 42),
                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2, cv2.LINE_AA)
    if latency_ms is not None:
        cv2.putText(bgr_frame, f"{settings.model_name} | {latency_ms:.0f} ms/inference",
                    (14, height - 16), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                    LIVE_GUIDE_BGR, 1, cv2.LINE_AA)

    return bgr_frame


# Module-level handoff between the Streamlit script thread and the WebRTC worker
# thread: st.session_state is not readable from the worker, so the live settings
# object is parked here instead.
_LIVE_SETTINGS_HOLDER = {}


def live_video_callback(frame):
    """WebRTC worker-thread callback — one call per incoming camera frame.

    Only every Nth frame is actually classified (`infer_every`); in between, the
    last EMA-smoothed result is redrawn. Without that, CPU-bound inference would
    stall the video pipeline and the label would strobe between classes."""
    import av

    settings = _LIVE_SETTINGS_HOLDER.get("settings")
    bgr_frame = frame.to_ndarray(format="bgr24")

    if settings is None or settings.model is None:
        return av.VideoFrame.from_ndarray(bgr_frame, format="bgr24")

    with settings.lock:
        if settings.mirror:
            bgr_frame = cv2.flip(bgr_frame, 1)

        settings.frame_i += 1
        due = (settings.frame_i % max(settings.infer_every, 1)) == 0

        if due or settings.smoothed is None:
            try:
                probs, cam_box, latency_ms = classify_roi(bgr_frame, settings)
                # EMA over class probabilities. Without it the label flickers
                # between classes on near-tie frames, which reads as "broken"
                # even when the model is behaving exactly as measured.
                if settings.smoothed is None:
                    settings.smoothed = probs
                else:
                    a = settings.ema_alpha
                    settings.smoothed = a * probs + (1.0 - a) * settings.smoothed
                settings.cam_box = cam_box
                settings.latency_ms = latency_ms
            except Exception:
                # A single bad frame must never kill the stream.
                pass

        out = draw_live_overlay(bgr_frame, settings, settings.smoothed,
                                settings.cam_box, settings.latency_ms)

    return av.VideoFrame.from_ndarray(out, format="bgr24")



# Custom CSS
st.markdown("""
<style>
    .stMainBlockContainer {
        padding-top: 30px !important;
    }
    .prediction-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        border-radius: 16px;
        padding: 2rem;
        color: white;
        text-align: center;
        margin: 1rem 0;
    }
    [data-theme="dark"] .prediction-card {
        background: linear-gradient(135deg, #4a5acf 0%, #5a3d8a 100%);
    }
    .prediction-label {
        font-size: 1rem;
        opacity: 0.9;
    }
    .prediction-value {
        font-size: 2.5rem;
        font-weight: 700;
        margin: 0.5rem 0;
    }
    .confidence-bar {
        background: rgba(255,255,255,0.3);
        border-radius: 10px;
        height: 12px;
        overflow: hidden;
        margin: 0.5rem 0;
    }
    .confidence-fill {
        height: 100%;
        border-radius: 10px;
        background: white;
    }
    .info-card {
        background: var(--secondary-background-color);
        color: var(--text-color);
        border-radius: 12px;
        padding: 1.5rem;
        margin: 0.5rem 0;
        border-left: 4px solid;
    }
    .model-unavailable {
        color: #e74c3c;
        font-size: 0.8rem;
    }
    [data-theme="dark"] .stProgress > div > div > div > div {
        background-color: var(--text-color);
    }
</style>
""", unsafe_allow_html=True)

# Tabs
tab_home, tab_live, tab_compare, tab_about = st.tabs(
    ["🏠 Home", "📹 Live", "📊 Compare", "ℹ️ About"]
)

with tab_home:
    # Left-right layout
    col_left, col_right = st.columns([1, 1])

    with col_left:
        # Model selector (segmented control)
        st.markdown("**Select Model**")
        model_labels = []
        model_files = {}
        for name, filename in MODELS.items():
            if name in FUSION_MODELS:
                # Needs BOTH the local .tflite file AND torch/transformers installed.
                available = os.path.exists(filename) and _clip_deps_available()
            else:
                available = os.path.exists(filename)
            model_files[name] = available
            if available:
                model_labels.append(name)
            else:
                model_labels.append(f"{name} (Not trained)")

        selected_model_label = st.segmented_control(
            "Model",
            model_labels,
            label_visibility="collapsed",
            default="ResNet50",
        )

        selected_model = selected_model_label.replace(" (Not trained)", "") if selected_model_label else "ResNet50"
        model_available = model_files.get(selected_model, False)

        # CLIP Verify toggle — only offered for CNN/MobileNetV2/ResNet50
        # (Feature Fusion already includes CLIP, no point toggling)
        use_clip_verify = False
        clip_verify_threshold = CLIP_VERIFY_DEFAULT_THRESHOLD
        clip_verify_available = os.path.exists(CLIP_LINEAR_PROBE_FILENAME) and _clip_deps_available()

        if selected_model in CLIP_VERIFY_MODELS:
            if clip_verify_available:
                use_clip_verify = st.toggle(
                    "🔍 CLIP Verify",
                    help=f"When ON, predictions with confidence below "
                         f"{CLIP_VERIFY_DEFAULT_THRESHOLD*100:.0f}% get double-checked by CLIP "
                         "Linear Probe. Tested on the benchmark test set this did NOT "
                         "improve accuracy (confidence isn't a reliable signal for this "
                         "model) — provided for experimentation, especially on real-world "
                         "photos the model wasn't trained on.",
                )
            else:
                st.caption("⚠️ CLIP Verify unavailable — missing `clip_linear_probe.pt` or CLIP dependencies.")

        # Upload photo
        uploaded_file = st.file_uploader(
            "Upload a photo of waste",
            type=["jpg", "jpeg", "png", "webp"],
        )

        # Camera input (toggle)
        use_camera = st.toggle("📷 Camera Mode")
        camera_file = st.camera_input("Take a photo") if use_camera else None

        # Use camera if available, otherwise use uploaded file
        if camera_file is not None:
            image = Image.open(camera_file).convert("RGB")
        elif uploaded_file is not None:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption="Uploaded Image", width=200)
        else:
            image = None

        # Start Detection button
        detect_clicked = st.button("🔍 Start Detection", use_container_width=True)

    with col_right:
        if not model_available:
            st.warning(f"⚠️ {selected_model} model is not trained yet. Please select CNN model.")
        elif image is None:
            st.info("📷 Please upload an image or take a photo")
        elif not detect_clicked:
            st.info("⬆️ Upload/take a photo and click Start Detection")
        else:
            # Run prediction
            model = load_model(MODELS[selected_model])

            if selected_model in FUSION_MODELS:
                # Dual-branch: ResNet50-style preprocessing for the image input,
                # plus a live CLIP feature for the second input (see predict_fusion).
                with st.spinner(f"AI Detecting with {selected_model}..."):
                    predictions = predict_fusion(model, image)
                    pred_index = np.argmax(predictions[0])
                    pred_class = CLASS_NAMES[pred_index]
                    confidence = float(predictions[0][pred_index]) * 100
            else:
                # Step 1+2: reproduce this model's training-time pipeline (resize
                # -> normalize) — all 3 remaining models share the same resize step.
                img_array = preprocess_image(image)
                img_array = np.expand_dims(img_array, axis=0)

                # Step 3: use this model's own normalization — not a shared /255.0 for everything
                img_array = PREPROCESS_FUNCS[selected_model](img_array)

                with st.spinner(f"AI Detecting with {selected_model}..."):
                    predictions = predict_with_model(model, img_array)
                    pred_index = np.argmax(predictions[0])
                    pred_class = CLASS_NAMES[pred_index]
                    confidence = float(predictions[0][pred_index]) * 100

                # CLIP Verify: only kicks in if the toggle is on AND this
                # prediction's own confidence fell below the chosen threshold.
                # See load_clip_verify_bundle()'s docstring — this is NOT
                # confirmed to improve accuracy on the benchmark test images.
                if use_clip_verify and (confidence / 100.0) < clip_verify_threshold:
                    verify_bundle = get_clip_verify_bundle()
                    with st.spinner("Confidence low — verifying with CLIP..."):
                        clip_predictions = predict_clip_verify(verify_bundle, image)
                        predictions = clip_predictions
                        pred_index = np.argmax(predictions[0])
                        pred_class = CLASS_NAMES[pred_index]
                        confidence = float(predictions[0][pred_index]) * 100
                    st.caption(f"🔍 {selected_model}'s confidence was below "
                               f"{clip_verify_threshold*100:.0f}% — final answer verified/overridden by CLIP.")
                elif use_clip_verify:
                    st.caption(f"✅ {selected_model} was confident enough — used directly, CLIP not consulted.")

            info = RECYCLE_INFO[pred_class]

            # Prediction card
            st.markdown(f"""
            <div class="prediction-card">
                <div class="prediction-label">Prediction</div>
                <div class="prediction-value">{info['icon']} {pred_class.title()}</div>
                <div class="confidence-bar">
                    <div class="confidence-fill" style="width: {confidence}%"></div>
                </div>
                <div class="prediction-label">Confidence: {confidence:.1f}%</div>
            </div>
            """, unsafe_allow_html=True)

            # All probabilities
            st.markdown("**📊 All Probabilities**")
            probs = {CLASS_NAMES[i]: float(predictions[0][i]) * 100 for i in range(len(CLASS_NAMES))}
            sorted_probs = dict(sorted(probs.items(), key=lambda x: x[1], reverse=True))
            for cls, prob in sorted_probs.items():
                st.progress(prob / 100, text=f"{cls.title()}: {prob:.1f}%")

            # Recycling guide
            st.markdown("**♻️ Recycling Guide**")
            col1, col2 = st.columns(2)
            with col1:
                st.markdown(f"""
                <div class="info-card" style="border-color: {info['color']}">
                    <strong>Bin:</strong> {info['bin']}<br>
                    <strong>Description:</strong> {info['description']}
                </div>
                """, unsafe_allow_html=True)
            with col2:
                st.markdown(f"""
                <div class="info-card" style="border-color: {info['color']}">
                    <strong>Tip:</strong> {info['tip']}
                </div>
                """, unsafe_allow_html=True)

with tab_live:
    st.markdown("### 📹 Live Camera Mode")

    # Set the reader's expectations before they see a box drawn on a video feed
    # and reasonably assume it is object detection. See the Live Camera Mode
    # section near the top of this file for why this wording matters.
    st.info(
        "**How to read this screen.** These models are *classifiers*, not object "
        "detectors — they output 4 class probabilities and no coordinates, so "
        "nothing here is locating an object for you. The **white square is a "
        "framing guide**: put your item inside it, and only those pixels get "
        "classified. The **coloured frame border + label** is the prediction for "
        "that square. The optional **amber box shows where the model looked** "
        "(Grad-CAM) — that is explainability, not detection."
    )

    if "live_settings" not in st.session_state:
        st.session_state.live_settings = LiveSettings()
    live_settings = st.session_state.live_settings
    _LIVE_SETTINGS_HOLDER["settings"] = live_settings

    live_available = {name: os.path.exists(MODELS[name]) for name in LIVE_MODELS}
    usable_live_models = [name for name, ok in live_available.items() if ok]

    if not usable_live_models:
        st.error(
            "⚠️ No model file available for Live Mode. Expected at least one of: "
            + ", ".join(f"`{MODELS[n]}`" for n in LIVE_MODELS)
        )
    else:
        col_cfg, col_cam = st.columns([1, 2])

        with col_cfg:
            st.markdown("**Model**")
            live_model_name = st.segmented_control(
                "Live model",
                usable_live_models,
                label_visibility="collapsed",
                default=usable_live_models[-1],
                key="live_model",
            ) or usable_live_models[-1]

            st.caption(
                "ResNet50+CLIP is not offered here — its second branch runs a full "
                "PyTorch CLIP encoder on every frame, which is far too slow for video."
            )

            roi_ratio = st.slider(
                "Framing guide size", 0.35, 1.0, 0.70, 0.05,
                help="How much of the frame gets classified. Smaller = the item "
                     "must fill a tighter square, which better matches the "
                     "single-object photos these models were trained on.",
            )

            infer_every = st.slider(
                "Classify every N frames", 1, 10, 3,
                help="Higher = smoother video, fewer inferences per second. "
                     "Inference is CPU-bound, so 1 will stutter on most machines.",
            )

            ema_alpha = st.slider(
                "Result smoothing", 0.05, 1.0, 0.50, 0.05,
                help="Exponential moving average over class probabilities. "
                     "1.0 = no smoothing (raw per-frame output, flickers on "
                     "near-ties); lower = steadier but slower to react.",
            )

            gradcam_supported = live_model_name in LIVE_GRADCAM_MODELS
            if gradcam_supported:
                use_gradcam = st.toggle(
                    "🔦 Show model attention (Grad-CAM)",
                    help="Draws a box around the region that most drove the "
                         "prediction, computed from the model's last conv layer. "
                         "This is an explainability overlay — NOT object "
                         "detection. Costs an extra forward+backward pass per "
                         "classified frame, so raise 'Classify every N frames' "
                         "if the video gets choppy.",
                )
            else:
                use_gradcam = False
                st.caption(
                    f"🔦 Grad-CAM unavailable for {live_model_name} — it ships as a "
                    "`.tflite` file, which exposes no intermediate feature map to "
                    "backprop through. Available on CNN and MobileNetV2."
                )

            mirror = st.toggle(
                "🪞 Mirror view", value=True,
                help="Flips the preview horizontally so it behaves like a mirror. "
                     "Applied before classification, which is harmless — these "
                     "models were trained with horizontal-flip augmentation.",
            )

        # Push the current widget values to the object the worker thread reads.
        live_model = load_model(MODELS[live_model_name])
        grad_model = get_gradcam_model(live_model_name) if use_gradcam else None
        if use_gradcam and grad_model is None:
            st.warning(
                "⚠️ Could not build the Grad-CAM model for this checkpoint — "
                "running without the attention box."
            )

        with live_settings.lock:
            if live_settings.model_name != live_model_name:
                # New model: drop the smoothed history so the old model's
                # probabilities don't bleed into the new one's first frames.
                live_settings.smoothed = None
                live_settings.cam_box = None
                live_settings.latency_ms = None
            live_settings.model = live_model
            live_settings.model_name = live_model_name
            live_settings.grad_model = grad_model
            live_settings.roi_ratio = roi_ratio
            live_settings.infer_every = infer_every
            live_settings.ema_alpha = ema_alpha
            live_settings.use_gradcam = bool(use_gradcam and grad_model is not None)
            live_settings.mirror = mirror

        with col_cam:
            if _WEBRTC_AVAILABLE:
                webrtc_streamer(
                    key="live-waste-classifier",
                    mode=WebRtcMode.SENDRECV,
                    video_frame_callback=live_video_callback,
                    media_stream_constraints={"video": True, "audio": False},
                    rtc_configuration={
                        "iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]
                    },
                    async_processing=True,
                )
                st.caption(
                    "First start takes a few seconds (camera permission + model "
                    "warm-up). If the stream never connects, your network may be "
                    "blocking WebRTC — use the snapshot fallback below instead."
                )
            else:
                st.warning(
                    "📹 Live video needs the `streamlit-webrtc` package, which is "
                    "not installed. Add it with:\n\n"
                    "```\npip install streamlit-webrtc av\n```\n\n"
                    "The snapshot fallback below works without it."
                )

        # Snapshot fallback — same ROI crop, same model, same overlay, on a single
        # still. Kept because WebRTC needs HTTPS + a reachable STUN server and can
        # fail on locked-down networks, and because it is the reliable path for a
        # live demo where a dropped video stream would be fatal.
        with st.expander("📸 Snapshot fallback (works without WebRTC)"):
            snapshot = st.camera_input("Take a photo", key="live_snapshot")
            if snapshot is not None:
                snap_rgb = np.array(Image.open(snapshot).convert("RGB"))
                snap_bgr = cv2.cvtColor(snap_rgb, cv2.COLOR_RGB2BGR)
                if mirror:
                    snap_bgr = cv2.flip(snap_bgr, 1)
                with st.spinner(f"Classifying with {live_model_name}..."):
                    snap_probs, snap_cam, snap_ms = classify_roi(snap_bgr, live_settings)
                overlaid = draw_live_overlay(
                    snap_bgr.copy(), live_settings, snap_probs, snap_cam, snap_ms
                )
                st.image(cv2.cvtColor(overlaid, cv2.COLOR_BGR2RGB), width="stretch")

                snap_index = int(np.argmax(snap_probs))
                snap_info = RECYCLE_INFO[CLASS_NAMES[snap_index]]
                st.markdown(
                    f"**{snap_info['icon']} {CLASS_NAMES[snap_index].title()}** — "
                    f"{snap_probs[snap_index] * 100:.1f}% · {snap_info['bin']} · "
                    f"{snap_ms:.0f} ms"
                )
                for i in np.argsort(snap_probs)[::-1]:
                    st.progress(
                        float(snap_probs[i]),
                        text=f"{CLASS_NAMES[i].title()}: {snap_probs[i] * 100:.1f}%",
                    )


with tab_compare:
    st.markdown("### 📊 Model Comparison")
    results = load_model_results()

    if results is None:
        st.warning(
            f"⚠️ `{MODEL_RESULTS_FILENAME}` not found next to app.py — "
            "this file holds the numbers for the charts below."
        )
    else:
        # Only the models actually selectable in the app — model_results.json also
        # keeps a "CLIP Linear Probe" entry for reference (used by the Colab
        # comparison notebook), but it's not a standalone deployable option here.
        model_names = [m for m in results["models"] if results["models"][m].get("file")]
        class_names = results["class_names"]
        test_n = results["test_set_size"]

        st.caption(
            f"Every number below comes from evaluating each model's actual deployed file "
            f"(the same .keras/.tflite in this repo) on the same shared {test_n}-image test split."
        )

        def show_exported_figure(filename: str, missing_label: str, width="stretch"):
            """Show a Colab-exported PNG from FIGURES_DIR, or a friendly
            'not uploaded yet' message instead of crashing if it's missing.
            width caps the display size — these PNGs are saved at 300dpi from
            Colab, so shown at "natural" size they'd render huge. Pass an int
            (pixels), 'stretch' (fill container - default), or 'content'."""
            path = os.path.join(FIGURES_DIR, filename)
            if os.path.exists(path):
                st.image(path, width=width)
            else:
                st.info(
                    f"📊 {missing_label} not available yet — export it from "
                    f"`04_Visualize_result_model.ipynb` and upload it to this repo as "
                    f"`{path}` to show it here."
                )

        # --- Overall test accuracy (headline chart, image left / metrics right) ---
        st.markdown("#### Overall Test Accuracy")
        st.caption('Higher is better — the single number that answers "which model is most accurate?"')

        # CNN, CLIP Linear Probe, then the rest of the deployed models — matches
        # the bar order in fig1_overall_accuracy.png
        acc_model_names = [model_names[0]] + (
            ["CLIP Linear Probe"] if "CLIP Linear Probe" in results["models"] else []
        ) + model_names[1:]
        col_chart, col_metrics = st.columns([3, 1])
        with col_chart:
            show_exported_figure("fig1_overall_accuracy.png", "Overall accuracy chart", width=650)
        with col_metrics:
            for name in acc_model_names:
                st.metric(name, f"{results['models'][name]['test_accuracy'] * 100:.2f}%")

        st.divider()


        # --- Row: Model Size vs. Accuracy | Per-Class F1-Score ---
        col_left, col_right = st.columns(2)

        with col_left:
            st.markdown("#### Model Size vs. Accuracy")
            st.caption(
                "Bigger dot = bigger file. Bottom-left = small & fast, top-right = big & accurate — "
                "this trade-off is why MobileNetV2 exists for phones even though ResNet50 scores higher."
            )
            show_exported_figure("fig7_size_vs_accuracy.png", "Model size vs. accuracy chart")

        with col_right:
            st.markdown("#### Per-Class F1-Score")
            st.caption(
                "Shows where each model struggles with a specific waste type. Darker green = "
                "better. CLIP Linear Probe is included as reference — it's not a selectable "
                "model in this app, only used internally by CLIP Verify."
            )
            # Deployed models first, then CLIP Linear Probe appended as a reference row
            f1_model_names = model_names + (
                ["CLIP Linear Probe"] if "CLIP Linear Probe" in results["models"] else []
            )
            f1_df = pd.DataFrame(
                {
                    name: [results["models"][name]["per_class"][c]["f1"] for c in class_names]
                    for name in f1_model_names
                },
                index=[c.title() for c in class_names],
            ).T
            st.dataframe(
                f1_df.style.format("{:.3f}").background_gradient(cmap="Greens", vmin=0.80, vmax=1.00)
            )

        st.divider()

        # --- Row: Confusion Matrices | CLIP Verify Effect ---
        col_left, col_right = st.columns(2)

        with col_left:
            st.markdown("#### Confusion Matrices")
            st.caption(
                "Which waste types each model confuses with which — the diagonal is correct "
                "predictions, everything off it is a specific error mode."
            )
            show_exported_figure("fig3_confusion_matrices.png", "Confusion matrix chart")

        with col_right:
            st.markdown("#### Does CLIP Verify Help?")
            st.caption(
                "CNN, MobileNetV2, and ResNet50 alone vs. paired with CLIP Verify, at the "
                "fixed 90% threshold used in this app."
            )
            show_exported_figure("fig8_clip_verify_effect.png", "CLIP Verify comparison chart")

        st.divider()

        # --- Row: ROC Curves | Confidence Distribution ---
        col_left, col_right = st.columns(2)

        with col_left:
            st.markdown("#### ROC Curves by Class")
            st.caption(
                "One-vs-rest ROC per waste type — how well each model separates that class "
                "from everything else. Higher AUC = better."
            )
            show_exported_figure("fig4_roc_curves.png", "ROC curve chart")

        with col_right:
            st.markdown("#### Confidence: Correct vs. Incorrect")
            st.caption(
                "If green (correct) and red (incorrect) overlap heavily, a model's confidence "
                "score isn't a reliable trust signal — this is why CLIP Verify doesn't help much."
            )
            show_exported_figure("fig5_confidence_distribution.png", "Confidence distribution chart")

        st.divider()

with tab_about:
    st.markdown("## About Smart Waste AI")
    st.markdown("""
    ### What is this?
    AI-powered waste classification system. Upload a photo, and the AI identifies the waste type and guides proper disposal.

    ### How does it work?
    - Multiple AI models trained on waste images
    - Classifies into 4 categories: **Glass, Metal, Paper, Plastic**
    - Provides confidence scores for each category

    ### Supported Models
    | Model | Status |
    |-------|--------|
    | CNN | ✅ Available |
    | MobileNetV2 | ✅ Available |
    | ResNet50 | ✅ Available |
    | ResNet50+CLIP | ✅ Available — dual-branch trained framework, 96.80% test accuracy |

    **CLIP Verify** (optional toggle for CNN/MobileNetV2/ResNet50): double-checks
    low-confidence predictions using CLIP Linear Probe. ⚠️ Tested on the benchmark
    test set, this did *not* improve accuracy — provided for experimentation on
    real-world photos instead.

    ### 📹 Live Camera Mode — what it does and does not do
    Live Mode classifies a live webcam feed and draws the result on the video.
    It is **not object detection**, and it is worth being precise about why:
    every model here is a **classifier**, whose entire output is 4 class
    probabilities. None of them predicts coordinates, so none of them can tell
    you *where* an item is in the frame.

    | On-screen element | What it actually means |
    |---|---|
    | White square | A **framing guide** — aim your item inside it. Only those pixels are classified. |
    | Coloured frame border + label | The predicted class + confidence **for that square**. |
    | Amber box (optional) | **Grad-CAM**: the region that most drove the prediction, read off the model's last conv layer. Explainability, not detection. Available on CNN and MobileNetV2 only — the `.tflite` models expose no intermediate feature map. |

    Real bounding boxes would need a detection architecture (YOLO or similar),
    which means training a new model — out of scope for this assignment.
    ResNet50+CLIP is excluded from Live Mode because its CLIP branch is far too
    slow to run per frame.

    ### Supported Waste Types
    | Category | Examples |
    |----------|----------|
    | 🍾 Glass | Bottles, jars, windows |
    | 🥫 Metal | Cans, foil, containers |
    | 📄 Paper | Newspapers, cardboard, books |
    | 🧴 Plastic | Bottles, containers, packaging |

    ### Team
    Built for AI Course Assignment
    """)
